fix: fix type mismatch for history_file argument
$ RUST_BACKTRACE=1 ./target/debug/emplace history .
thread 'main' panicked at src/main.rs:155:18:
Mismatch between definition and access of `history_file`. Could not downcast to std::path::PathBuf, need to downcast to camino::Utf8PathBuf

stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: clap_builder::parser::error::MatchesError::unwrap
             at /Users/rui/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.23/src/parser/error.rs:32:9
   3: clap_builder::parser::matches::arg_matches::ArgMatches::get_one
             at /Users/rui/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.23/src/parser/matches/arg_matches.rs:119:9
   4: emplace::safe_main
             at /Users/rui/Downloads/brew/emplace/src/main.rs:154:39
   5: emplace::main
             at /Users/rui/Downloads/brew/emplace/src/main.rs:193:23
   6: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20241128-8064-v5d6qj/rustc-1.83.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Signed-off-by: Rui Chen <rui@chenrui.dev>